version: "3.9"

services:
  mending-depot:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: mending-depot-db
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    volumes:
      - mending-depot-db-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mending-depot-db
    ports:
      - 3306:3306

volumes:
  mending-depot-db-data: