version: "3.9"

services:
  mending-depot-app-local:
    image: mending-depot-app
    container_name: mending-depot-app
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    network_mode: host