name: Install and Run App on Server

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Clone Repo
          uses: actions/checkout@v3

        - name: Make SSH Folder
          run: |
            mkdir -p ~/.ssh

        - name: Add Private Key to SSH
          env:
            DEPLOY_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          run: |
            echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_ed25519
            echo "$DEPLOY_SSH_KEY"

        - name: Allow Permissions on SSH Key File
          run: |
            chmod 600 ~/.ssh/id_ed25519

        - name: Add Server to Known Hosts
          env:
            LIGHTSAIL_IP: ${{ secrets.LIGHTSAIL_IP }}
          run: |
            ssh-keyscan -H $LIGHTSAIL_IP >> ~/.ssh/known_hosts
            
        - name: Copy Files to Server
          env:
            LIGHTSAIL_IP: ${{ secrets.LIGHTSAIL_IP }}
            LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
          run: |
            rsync -avz --exclude='.git*' --exclude='.github' ./$LIGHTSAIL_USERNAME@$LIGHTSAIL_IP:~/mending-depot-app

        - name: Run Deploy Script
          env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
            URL: ${{ secrets.URL }}
            NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
            NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
            APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
            APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
          run: |
            ssh $LIGHTSAIL_USERNAME@$LIGHTSAIL_IP 'bash mending-depot-app/scripts/deploy.sh $DATABASE_URL $DATABASE_PASSWORD $URL $NEXTAUTH_URL $NEXTAUTH_SECRET $APP_CLIENT_ID $APP_CLIENT_SECRET'

        - name: Deployment completed Successfully
          run: echo "Deployment completed successfully"
